version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend

  nodeapp:
    build: ./nodeapp
    container_name: nodeapp
    ports:
      - "8787:8787"

  pythonapp:
    build: ./pythonapp
    container_name: pythonapp
    ports:
      - "8888:8888"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - nodeapp
      - pythonapp
