version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend

  nodeapp:
    build: ./nodeapp
    container_name: nodeapp
    ports:
      - "8788:8787"   # Host 8788 → Container 8787

  pythonapp:
    build: ./pythonapp
    container_name: pythonapp
    ports:
      - "8889:8888"   # Host 8889 → Container 8888

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - nodeapp
      - pythonapp

